version: "3.8"

services:
  app:
    build: .
    container_name: voting-app
    ports:
      - "8090:8090"
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGODB_URI=mongodb://mongo:27017
    depends_on:
      - redis
      - mongo
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis
    volumes:
      - redis-data:/data
    networks:
      - app-network

  mongo:
    image: mongo:7
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
  redis-data:
