FROM jenkins/jenkins:lts

USER root

RUN apt-get update && apt-get install -y curl

RUN curl -LO "https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl" \
 && chmod +x kubectl \
 && mv kubectl /usr/local/bin/

USER jenkins
